apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibWlrby1wcmFjdGljdW0iLCJwYXNzd29yZCI6ImdocF9BR0EweFZoaGpETzRhRTZLdGZCWXk4UDFNMlI5WFMxTWtudUoiLCJlbWFpbCI6ImplbmZsb3dlcl85N0BtYWlsLnJ1IiwiYXV0aCI6ImJXbHJieTF3Y21GamRHbGpkVzA2WjJod1gwRkhRVEI0Vm1ob2FrUlBOR0ZGTmt0MFprSlplVGhRTVUweVVqbFlVekZOYTI1MVNnPT0ifX19
